pipeline {
	agent {
		docker {
			image 'python:2.7.16-slim'
		}
	}

	stages {
		stage('build') {
			when {
				changeset '**/vote/**'
			}

			steps {
				echo 'Compiling vote app'
				sh 'pip install -i requirements.txt'
			}
		}
		stage('test') {
			when { 
                                changeset '**/vote/**'
                        }

                        steps { 
                                echo 'Running Unit Test on vote app'
                                sh 'nosetests -v'
                        }
                }
	}

	post {
		always {
			echo 'Building multibranch pipeline for vote is completed..'
		}
	}
}
