pipeline {
	agent {
		docker {
			image 'python:2.7.16-slim'
			args '--user root'
		}
	}
	stages {
		stage('build') {
			steps {
				echo 'Compiling vote app'
				dir('vote') {
					sh 'pip install -r requirements.txt'
				}
			}
		}
		stage('test') {
			steps { 
                echo 'Running Unit Test on vote app'
                dir('vote') {
					sh 'nosetests -v'
				}
			}
        }
	}
	post {
		always {
			echo 'Building multibranch pipeline for vote is completed..'
		}
	}
}
